AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GearSwap - Streamlined SAM Template

Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Runtime: python3.12
    Architectures: 
      - x86_64
    Environment:
      Variables:
        DB_HOST: "gearswapdb.cfs4ukyuq1o9.us-east-2.rds.amazonaws.com"
        DB_USER: "postgres"
        DB_PASSWORD: "postgres"
        DB_PORT: "5432"
        WORKOS_CLIENT_ID: "client_01JA67H9AXQGPC28X9JHF3TB0F"
        WORKOS_API_KEY: "sk_test_a2V5XzAxSkE2N0g4UllEODUxMEVSVkFCRjJEN1czLGNISXJXdmsyck84QjJoZVJ2c0dNdGx4SmY"
        COGNITO_USER_POOL_ID: "us-east-2_pqVjVG3qi"
        COGNITO_CLIENT_ID: "5hu1dh5v8aj9cl35je2ptgqg9h"
    VpcConfig:
      SecurityGroupIds: 
        - sg-03c19dd98d5aa9665
        - !Ref LambdaSecurityGroup
      SubnetIds: !Ref SubnetIds
    Layers:
      - !Ref DependenciesLayer

Parameters:
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets where the Lambda functions will be deployed

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: RDSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds-db:connect
                Resource: '*'

  AuthFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CognitoInvokeAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cognito-idp:AdminInitiateAuth'
                  - 'cognito-idp:AdminCreateUser'
                  - 'cognito-idp:AdminSetUserPassword'
                Resource: '*' 

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: vpc-05b31ac071b580a8c
      SecurityGroupEgress:
        - IpProtocol: -1
          # FromPort: -1
          # ToPort: -1
          CidrIp: 0.0.0.0/0

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: dependencies-layer
      Description: Dependencies for the Lambda functions
      ContentUri: ./ 
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

  gearSwap:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: gearPool
      LambdaConfig:
        UserMigration: !GetAtt AuthFunction.Arn

  # Auth Function
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: auth.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      VpcConfig:
        SecurityGroupIds: 
          - !Ref LambdaSecurityGroup
        SubnetIds: !Ref SubnetIds
  
  # # Login Function
  # loginFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: auth/
  #     Handler: login.lambda_handler
  #     Runtime: python3.12
  #     Architectures:
  #       - x86_64
  #     Events:
  #       Login:
  #         Type: Api
  #         Properties:
  #           Path: /login/{email}
  #           Method: POST

  # User Functions
  UserFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /users
            Method: POST
        GetAllUsers:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /users
            Method: GET
        GetUserById:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /users/{Id}
            Method: GET
        UpdateUser:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /users/{Id}
            Method: PUT
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /users/{Id}
            Method: DELETE
        GetUsersFollowing:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /users/following/{Id}
            Method: GET
        GetUsersFollowers:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /users/followers/{Id}
            Method: GET

  # UserProfile Functions
  UserProfileFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: userProfile/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        CreateProfile:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /userProfile/{Id}
            Method: POST
        GetProfile:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /userProfile/{Id}
            Method: GET
        UpdateProfile:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /userProfile/{Id}
            Method: PUT
        DeleteProfile:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /userProfile/{Id}
            Method: DELETE

  # Cart Functions
  CartFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cart/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        CreateProfile:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /cart/{Id}
            Method: POST
        GetProfile:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /cart/{Id}
            Method: GET
        UpdateProfile:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /cart/{Id}
            Method: PUT
        DeleteProfile:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /cart/{Id}
            Method: DELETE

  # Posts Functions
  PostsFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: posts/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        CreatePost:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /posts/{userId}
            Method: POST
        GetAllPosts:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /posts
            Method: GET
        GetPostById:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /posts/{userId}/{postId}
            Method: GET
        UpdatePost:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /posts/{userId}/{postId}
            Method: PUT
        DeletePost:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /posts/{userId}/{postId}
            Method: DELETE
        GetPostsByFilter:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /posts/filter/{userId}
            Method: GET

  # Search Functions
  SearchFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: search/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        PostSearch:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /search/{userId}
            Method: POST
        GetSearchHistory:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /search/{userId}
            Method: GET
        DeleteSearch:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /search/{userId}/{searchId}
            Method: DELETE

  # LikedPost Functions
  LikedPostFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: likedPosts/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        AddLikedPost:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /likedPosts/{userId}
            Method: POST
        GetLikedPosts:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /likedPosts/{userId}
            Method: GET
        RemoveLikedPost:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /likedPosts/{userId}/{postId}
            Method: DELETE
        GetLikedPostById:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /likedPosts/{userId}/{postId}
            Method: GET
  
  # Outfit Functions
  OutfitFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: outfit/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        CreateOutfit:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /outfit/{userId}
            Method: POST
        GetOutfits:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /outfit/{userId}
            Method: GET
        PutOutfit:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /outfit/{userId}/{outfitId}
            Method: PUT
        DeleteOutfit:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /outfit/{userId}/{outfitId}
            Method: DELETE
        GetOutfitById:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /outfit/{userId}/{outfitId}
            Method: GET
        AddItemByOutfitId:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /outfit/item/{userId}/{outfitId}
            Method: POST
        RemoveItemByOutfitId:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /outfit/item/{userId}/{outfitId}
            Method: DELETE

  # Styler Functions
  StylerFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: styler/
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        RefreshStyler:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /styler/{userId}
            Method: POST
        GetStyleTips:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /styler/{userId}
            Method: GET
        GenerateOutfitByWardrobe:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /styler/wardrobe/{userId}
            Method: POST
        GetSimilarItems:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /styler/similar/{postId}
            Method: GET
        GetTrendingItems:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /styler/trending
            Method: GET
        GetStyleAnalysis:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /styler/analysis/{userId}
            Method: GET
        GenerateOutfitRec:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /styler/outfit/{userId}
            Method: POST
        GenerateItemRec:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /styler/item/{userId}
            Method: POST
        GetStylePreferences:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /styler/preferences/{userId}
            Method: GET
        PutStylePreferences:
          Type: Api
          Properties:
            RestApiId: !Ref gearSwap
            Path: /styler/preferences/{userId}
            Method: PUT

Outputs:
  gearSwapUrl:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${gearSwap}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UserFunctionsArn:
    Description: User Functions ARN
    Value: !GetAtt UserFunctions.Arn
  UserProfileFunctionsArn:
    Description: UserProfile Functions ARN
    Value: !GetAtt UserProfileFunctions.Arn
  CartFunctionsArn:
    Description: Cart Functions ARN
    Value: !GetAtt CartFunctions.Arn
  PostsFunctionsArn:
    Description: Posts Functions ARN
    Value: !GetAtt PostsFunctions.Arn
  SearchFunctionsArn:
    Description: Search Functions ARN
    Value: !GetAtt SearchFunctions.Arn
  LikedPostFunctionsArn:
    Description: LikedPost Functions ARN
    Value: !GetAtt LikedPostFunctions.Arn
  OutfitFunctionsArn:
    Description: Outfit Functions ARN
    Value: !GetAtt OutfitFunctions.Arn
  StylerFunctionsArn:
    Description: Styler Functions ARN
    Value: !GetAtt StylerFunctions.Arn
  AuthFunctionArn:
    Description: Auth Function ARN
    Value: !GetAtt AuthFunction.Arn